# see: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/deploy-linux-vm?view=azure-devops&tabs=java
variables:
  #isRelease: "$[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/1.0.0')]"
  isDevelop: "$[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]"

trigger:
  - develop
# build agent pool default가 dtonic꺼
# see: https://dev.azure.com/dtonic/_settings/agentpools
pool:
  name: default
# develop branch build
stages: 
- stage: AdvancedDevelopIngestManagerService
  displayName: Build advanced develop ingestManager service
  jobs:
    - job: build
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml' # Maven Pom.xml 경로
          publishJUnitResults: false 
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
        displayName: 'IngestManager Packaging'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/docker'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/pipeline'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/target'
          Contents: '**.jar'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/pipeline/develop'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'ingestManager'
          publishLocation: 'Container'

# develop branch publish
- stage: DevelopbedRelease
  #condition: and(succeeded(), eq(variables.isDevelop, true))
  jobs:
    - deployment: IngestManager_Dev_123Server
      # 배포할 Envornment
      environment:
        name: "Develop_ENV_123server"
        resourceType: VirtualMachine
      variables:
        baseFolder: /usr/local/lib/ingestManager
        AdvancedAnalysisJarFile: $[ stageDependencies.AdvancedAnalysisService.build.outputs['buildResult.jarFileName'] ]
      strategy:
        runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                inputs:
                  script: 'cp -r ./ingestManager/pipeline /pipeline'
                  workingDirectory: '$(Agent.BuildDirectory)'
              - task: CmdLine@2
                inputs:
                  script: 'chmod 771 /pipeline/deploy.sh'
                  workingDirectory: '$(Agent.BuildDirectory)'
              - task: CmdLine@2
                inputs:
                  script: 'sh /pipeline/deploy.sh'
                  workingDirectory: '$(Agent.BuildDirectory)'