application:
  title: D.Hub-Ingest-Manager
  version: 1.2.1

spring:
  application:
    name: dh-ingest-manager

  thymeleaf:
    prefix: classpath:/static/
    cache: false

  security:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/dhub?currentSchema=ingest_manager
    username: postgres
    password: postgres


server:
  port: 8099
  servlet:
    context-path: /
    session.timeout: 60m
  tomcat:
    remote-ip-header: x-forwarded-for
  ssl:
    enabled: false
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-store-password: srd5wjn9

## Logging
logging.config: classpath:logback-spring.xml
logging.base.dir: logs

# HTTP retrieve
datacore:
  http:
    binding:
      response:
        log.yn: Y
      cause:
        msg:
          trace:
            key: x-detail-error-key
            value: BBBBB
          level: 3

cityhub:
  client:
    clientId: qti7lRjyOa44u4Vb6tIp
    clientSecret: 8bhv1xIyH76NiDaXgU8agc31YTUd9g7g
    userAuthorizationUri: http://110.45.181.72:30000/oauth2.0/authorize
    accessTokenUri: http://110.45.181.72:30000/oauth2.0/token
    publicKeyUri: http://110.45.181.72:30000/security/publickey
    logoutUri: http://110.45.181.72:30000/security/logout
    userInfoUri: http://110.45.181.72:30000/security/users
    redirectUri: http://localhost:8099/accesstoken
  security:
    accessRole:
      user: Dhub_User
    
  datacore:
    manager:
      url: http://211.253.243.123:8080
    ingestInterface:
      url: http://211.253.243.123:8081

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000
  read.timeout: 10000
  validate.after.inactivity: 2000

nifi:
  version: 1.23.0
  url: http://localhost:28008
  user: admin
  password: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
  template:
    init: true
  merge:
    bulk.min.size: 10
    bulk.max.size: 100
    batch.interval: 1 # sec
