spring:
  application:
    name: dh-datacore-ui

  thymeleaf:
    prefix: classpath:/static/
    cache: false

  security:
    enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.12.0.11:5432/datacore
    username: keti_datacore
    password: keti123

    retrieve:
      use.yn: Y
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.12.0.11:5432/datacore
      username: keti_datacore
      password: keti123
server:
  port: 8080
  servlet:
    context-path: /
    session.timeout: 60m

## Logging
logging.config: classpath:logback-spring.xml
logging.base.dir: logs

# HTTP retrieve
datacore:
  http:
    binding:
      response:
        log.yn: Y
      cause:
        msg:
          trace:
            key: x-detail-error-key
            value: BBBBB
          level: 3

cityhub:
  client:
    clientId: FGppHOCNp8LC69pZnjSN
    clientSecret: fV83KX75CRXJNTF81F7QWHuG0OFhfh5u
    userAuthorizationUri: http://203.253.128.181:30084/oauth2.0/authorize
    accessTokenUri: http://10.7.0.22:30000/oauth2.0/token
    publicKeyUri: http://10.7.0.22:30000/security/publickey
    logoutUri: http://10.7.0.22:30000/security/logout
    userInfoUri: http://10.7.0.22:30000/security/users
    redirectUri: http://203.253.128.181:16608/accesstoken

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000
  read.timeout: 10000
  validate.after.inactivity: 2000
