application:
  title: D.Hub-Ingest-Manager
  version: 1.2.0

spring:
  application:
    name: dh-ingest-manager

  thymeleaf:
    prefix: classpath:/static/
    cache: false

  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgis4:5432/smart_city?currentSchema=ingest_manager
    username: postgres
    password: postgres
    logging:
      use.yn: N
      moduleName: ingest_manager
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/ingestmanager?currentSchema=logging
      username: postgres
      password: postgres
    retrieve:
      use.yn: N
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.12.0.11:5432/datacore
      username: keti_datacore
      password: keti123

server:
  port: 8099
  servlet:
    context-path: /
    session.timeout: 60m
  tomcat:
    remote-ip-header: x-forwarded-for
  ssl:
    key-store: file:///keystore.jks
    key-store-type: JKS
    key-store-password: srd5wjn9

## Logging
logging.config: file:///logback-spring-rel.xml
logging.base.dir: logs
# HTTP retrieve
datacore:
  http:
    binding:
      response:
        log.yn: Y
      cause:
        msg:
          trace:
            key: x-detail-error-key
            value: BBBBB
          level: 3

cityhub:
  security:
    accessRole:
      user: Dhub_User

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000
  read.timeout: 10000
  validate.after.inactivity: 2000
nifi:
  version: 1.23.0
  url: http://localhost:28008
  user: admin
  password: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
  template:
    init: true
