version: "3"
services:
  ingestmanager:
    build:
      context: ./
      args:
        - version=1.1.3
    ports:
      - 8099:8099
#    network_mode: host
    depends_on:
      - nifi
    restart: always
    volumes:
      - ../application-common.yml:/application-common.yml
      - ./logs/ingestManager:/logs
    networks:
      - datacore_default

  nifi:
    container_name: nifi
    #image: justin0215/nifi-dtonic:Beta
    build:
      context: ./
      dockerfile: Dockerfile.NiFi
    user: "0:0"
    environment:
      NIFI_WEB_PROXY_HOST: '110.45.181.72:8444' # 임시 변경
      nifi_web_https_host: '110.45.181.72'
      NIFI_WEB_HTTPS_PORT: 8443 # 임시 변경
      TZ: Asia/Seoul
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin1234567
    volumes:
      #- ./nifi/conf:/opt/nifi/nifi-current/conf
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./logs/nifi:/opt/nifi/nifi-current/logs
    ports:
#      - 20000-20099:20000-20099/tcp
#      - 8443:8443
      - 21100-21199:20000-20099/tcp # 포트 정보 변경(임시)
      - 8444:8443 # 포트 정보 변경(임시)
      #http - 8080/https - 8443
      #      - 8008:8008
    networks:
      - datacore_default


networks:
  datacore_default:
    external: true