FROM adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine
VOLUME /tmp
ARG VERSION

# 나중에 Nexus에서 받아오도록 수정
ADD ./jar/d-hub-ingest-module-${VERSION}.jar /app.jar
# ADD application-dtonic.yml /application-dtonic.yml
# ADD logback-spring.xml /logback-spring.xml
ENTRYPOINT ["java","-jar","/app.jar","--spring.profiles.active=dtonic"]