version: "3"
services:
  ingestmanager:
    build:
      context: ./ingestManager
    ports:
      - 8094:8099
    environment:
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_JDBCURL: jdbc:postgresql://211.253.243.121:8098/ingestmanager_dev_123?currentSchema=ingest_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post_1
      CITYHUB_CLIENT_CLIENTID: tPXae1PEtMhdlJ7IYnG9
      CITYHUB_CLIENT_CLIENTSECRET: pJ2uUujrz08QdL3l1oyzC4csGa7Q48Sh
      CITYHUB_CLIENT_USERAUTHORIZATIONURI: https://openlab122.dtonic.io:30000/oauth2.0/authorize
      CITYHUB_CLIENT_ACCESSTOKENURI: https://openlab122.dtonic.io:30000/oauth2.0/token
      CITYHUB_CLIENT_PUBLICKEYURI: https://openlab122.dtonic.io:30000/security/publickey
      CITYHUB_CLIENT_LOGOUTURI: https://openlab122.dtonic.io:30000/security/logout
      CITYHUB_CLIENT_USERINFOURI: https://openlab122.dtonic.io:30000/security/users
      CITYHUB_CLIENT_REDIRECTURI: https://openlab123.dtonic.io:8099/accesstoken
      CITYHUB_SECURITY_ACCESSROLE_USER: Dhub_User
      CITYHUB_DATACORE_MANAGER_URL: http://211.253.243.122:8080
      CITYHUB_DATACORE_INGESTINTERFACE_URL: http://211.253.243.122:8081
      NIFI_URL: https://211.253.243.121:8443
      NIFI_USER: admin
      NIFI_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      SPRING_SECURITY_ENABLED: "false"
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY-STORE: classpath:keystore.jks
      SERVER_SSL_KEY-STORE-TYPE: JKS
      SERVER_SSL_KEY-STORE-PASSWORD: srd5wjn9
    network_mode: host
